version: "2"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - host
  db-api-gateway:
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: myselect
      POSTGRES_PASSWORD: noadminno
      POSTGRES_DB: apigateway
    networks:
      - host
  db-post:
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: myselect
      POSTGRES_PASSWORD: noadminno
      POSTGRES_DB: post
    networks:
      - host
  db-user:
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: myselect
      POSTGRES_PASSWORD: noadminno
      POSTGRES_DB: user
    networks:
      - host
  db-comment:
    image: postgres:12
    network_mode: "host"
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: myselect
      POSTGRES_PASSWORD: noadminno
      POSTGRES_DB: comment
    networks:
      - host
#  ms-apigateway:
#    image: node
#    ports:
#      - 8000:8000
#    build: "./backend/ms-api-gateway"
#    depends_on:
#      - "db-api-gateway"
#      - "ms-user"
#      - "ms-comment"
#      - "ms-post"
#  ms-user:
#    image: node
#    ports:
#      - 8001:8000
#    build: "./backend/ms-user"
#    depends_on:
#      - "db-user"
#  ms-comment:
#    image: node
#    ports:
#      - 8002:8000
#    build: "./backend/ms-comment"
#    depends_on:
#      - "db-comment"
#  ms-post:
#    image: node
#    ports:
#      - 8003:8000
#    build: "./backend/ms-post"
#    depends_on:
#      - "db-post"
#  front-post:
#    image: node
#    ports:
#      - 3002:3000
#    depends_on:
#      - "ms-apigateway"
#  front-comment:
#    image: node
#    ports:
#      - 3006:3000
#    depends_on:
#      - "ms-apigateway"
#  front-user:
#    image: node
#    ports:
#      - 3005:3000
#    depends_on:
#      - "ms-apigateway"
#  front-shell:
#    image: node
#    ports:
#      - 3000:3000
#    depends_on:
#      - "ms-apigateway"

networks:
  host:
    external: true